### ISSUE TITLE
{if} not necessary check HTML tag

### ISSUE THREAD

**Issue by Aldecoez** [Floxim/floxim#2]
Exemple return Floxim html parser error:

```
<div>
    {if true}
        </div>
        <div class="clearfix"></div>
    {else}
        </div>
    {/if}
```

**Comment by dubrowsky** [comment]
Hi! 
Floxim is not Smarty, although sometimes it looks like Smarty ;) 

Template instructions are based on node tree, so it must be correct. Read more about template engine: http://floxim.org/Template-engine-reference

For your example snippet the right way is to add the condition around the clearfix tag. This code is correct and seems to be more readable:

```
<div>
    [content]
    <div fx:if="$need_clearfix" class="clearfix"></div>
</div>
```

or the same thing in Smarty-like syntax (two lines more, but sometimes easier to understand):

```
<div>
    [content]
    {if $need_clearfix}
        <div class="clearfix"></div>
    {/if}
</div>
```

By the way, it also relates to header/footer templates. Floxim doesn't let you create something like this:

```
{* header.tpl *}
{template id="header"}
    <body>
        <div class="wrap_one">
            <div class="wrap_two">
                <div class="extra_wrap">
{/template}


{* footer.tpl *}
{template id="footer"}
                </div> {* /content *}
            </div> {* hm, may be some wrapper *}
        </div> {* should i add one more?? o_0 *}
    </body>
{/template}
```

In this aspect Floxim template language is like XSLT (but with shorter and not very strict syntax).
